name: babyfood
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+9

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  get_it: ^7.6.4
  flutter_html: ^3.0.0-beta.2
  flutter_layout_grid: '^2.0.5'
  flutter_math_fork: '^0.7.1'
  flutter_svg: ^2.0.10+1
  go_router: ^12.1.3
  flutter_html_table: ^3.0.0-beta.2
  flutter_cache_manager: ^3.3.1
  intl: ^0.19.0
  rate_my_app: ^2.0.0
  flutter_native_splash: ^2.3.10
  json_annotation: ^4.8.1
  zoom_tap_animation: ^1.1.0
  carousel_slider: ^4.2.1
  yandex_mobileads: ^6.3.0
  url_launcher: ^6.2.4
  mysql1: ^0.20.0
  flutter_spinkit: ^5.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  windows:
    generate: true
    image_path: "assets/images/icon2.png"
    icon_size: 48 # min:48, max:256, default: 48


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/noimage.jpg
    - assets/images/launchframe.png
    - assets/images/icon2.png
    - assets/images/icon3.png
    - assets/images/screenshot0.jpg
    - assets/images/screenshot1.png
    - assets/images/screenshot2.png
    - assets/images/screenshot3.png
    - assets/images/screenshot4.png
    - assets/images/error.svg
