// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhhRUDdZp-R-XwUnWhC2cVr09IFLM6Xqs',
    appId: '1:154376222956:web:4f9355d93ae969dda94dc9',
    messagingSenderId: '154376222956',
    projectId: 'babyfood-auth',
    authDomain: 'babyfood-auth.firebaseapp.com',
    storageBucket: 'babyfood-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGRBKU2lcTIhXdnU1Qvgg0mRaJ6kGnxjk',
    appId: '1:154376222956:android:0d69efb207a79345a94dc9',
    messagingSenderId: '154376222956',
    projectId: 'babyfood-auth',
    storageBucket: 'babyfood-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3thhf7C2hMgfeNrnBIXxjShqTMyLj0JQ',
    appId: '1:154376222956:ios:7069e3ba318e108ca94dc9',
    messagingSenderId: '154376222956',
    projectId: 'babyfood-auth',
    storageBucket: 'babyfood-auth.appspot.com',
    iosBundleId: 'com.babylabpro.babyfood',
  );
}
